pipeline{
    agent any
        stages{
            stage('System details'){
                steps{
                    sh '''
                    echo -e "\n \n"
                    echo -e "\t\t SYSTEM DETAILS"
                    echo -e "\n \n"
                    uname -a
                    '''
                }
            }
            stage('Memory details'){
                steps{
                    sh '''
                    echo -e "\n \n"
                    echo -e "\t\t  MEMORY DETAILS"
                    echo -e "\n \n"
                    free
                    '''
                }
            }
            stage('CPU details'){
                steps{
                    sh '''
                    echo -e "\n \n"
                    echo -e "\t\t CPU DETAILS"
                    echo -e "\n \n"
                    lscpuk
                    '''
                }
            }
            stage('Disk details'){
                steps{
                    sh '''
                    echo -e "\n \n"
                    echo -e "\t\t DISK DETAILS"
                    echo -e "\n \n"
                    df -kh
                    '''
                }
            }
        }
}
